export const bhavanCenters = [
  {
    name: "Ahmedabad",
    position: [23.02579, 72.58727],
    key: "ahmedabad",
    address:
      "Bhavan’s College Campus, Near Rifle Club, Lady Vidyagauri Neelkanth Marg, Khanpur, Ahmedabad 380 001.",
    maps: "",
    website: "https://www.hbicm.in",
    email: "hbiahmedabad@gmail.com",
  },
  {
    name: "Bharuch",
    position: [21.69482, 72.9805],
    key: "bharuch",
    address:
      "C/o, Narmada College of Management, Shuklatirth Road, Zadeshwar, Bharuch 392011",
    maps: "",
    website: "",
    email: "bvbbharuch@gmail.com",
  },
  {
    name: "Kottayam",
    position: [9.66667, 76.66667],
    key: "kottayam",
    address:
      "Kottayam Kendra, First Floor, Gargi Bldgs., No. XII/1289D, Nr. Manorama Jn., Erayilkadavu Road, Kottayam 686001",
    maps: "",
    website: "",
    email: "bhavanskottayam@gmail.com",
  },
  {
    name: "Thiruvananthapuram",
    position: [8.60399, 76.98574],
    key: "thiruvananthapuram",
    address:
      "Bhavan’s Tower, Kattu Road, Poojappura, Thiruvananthapuram 695012",
    maps: "",
    website: "",
    email: "bvbtvmkendra@gmail.com",
  },
  {
    name: "Thrissur",
    position: [10.51667, 76.21667],
    key: "thrissur",
    address: "Thiruvambady Buildings, Round West, Thrissur 680001",
    maps: "",
    website: "",
    email: "bvbthrissur@gmail.com",
  },
  {
    name: "Kolkata",
    position: [22.56263, 88.36304],
    key: "kolkata",
    address: "Block FA/ Sector III, Salt Lake City, Kolkata 700097",
    maps: "",
    website: "",
    email: "admin@bimskol.org",
  },
  {
    name: "Faridabad",
    position: [28.41124, 77.31316],
    key: "fardiabad",
    address: "Institutional Area, Central Green, NH-3, Faridabad 121 001",
    maps: "",
    website: "",
    email: "yadvindersandhu@yahoo.co.in",
  },
  {
    name: "Solan",
    position: [30.904486, 77.096736],
    key: "solan",
    address: "Petrol Pump, Kundhidhar, Rajgarh Road, Shamti, Solan 173212",
    maps: "",
    website: "",
    email: "brijenderpanwar@gmail.com",
  },
  {
    name: "Hyderabad",
    position: [17.38405, 78.45636],
    key: "hyderabad",
    address:
      "Kulapati Munshi Sadan, 5-9-1105, Bashirbagh King Kothi Road, Hyderabad 500029",
    maps: "",
    website: "",
    email: "bvbhyd.bccm@gmail.com",
  },
  {
    name: "Chandigarh",
    position: [30.7333148, 76.7794179],
    key: "chandigarh",
    address: "Plot No.5,Sector 27-B, 5,Madhya Marg, Chandigarh 160019",
    maps: "",
    website: "",
    email: "bharatiya.bhavan@gmail.com",
  },
  {
    name: "Jamnagar",
    position: [22.47292, 70.06673],
    key: "jamnagar",
    address: "A.K. Doshi Mahila College, Mahila College Marg, Jamnagar 361008",
    maps: "",
    website: "",
  },
  {
    name: "Bangalore",
    position: [12.97194, 77.59369],
    key: "bangalore",
    address: "Race Course Road, Bangalore 560001",
    maps: "",
    website: "www.hbcollege.org",
    email: "hbcollege18@yahoo.co.in",
  },
  {
    name: "Mangalore",
    position: [12.91723, 74.85603],
    key: "mangalore",
    address: "Pandeshwar, Mangalore 575001",
    maps: "",
    website: "",
    email: "bvb_mlr@yahoo.co.in",
  },
  {
    name: "Belgaum",
    position: [15.85212, 74.50447],
    key: "belgaum",
    address: "G.C.C.Campus, Tilakwadi, Belgaum 590006",
    maps: "",
    website: "",
    email: "",
  },
  {
    name: "Gulbarga",
    position: [17.33583, 76.83757],
    key: "gulbarga",
    address: "Aiwan-E-Shahi Road, Gulbarga 585 102",
    maps: "",
    website: "",
    email: "rbkonda@yahoo.com",
  },
  {
    name: "Nagpur",
    position: [21.14631, 79.08491],
    key: "nagpur",
    address: "Lala Lajpatrai Marg, Near Museum, Civil Lines, Nagpur 440001",
    maps: "",
    website: "",
    email: "",
  },
  {
    name: "Pune",
    position: [18.51957, 73.85535],
    key: "pune",
    address:
      "407/408, K.M. Munshi Marg, Bharatiya Vidya Bhavan Chowk, Shivajinagar, Pune 411016",
    maps: "",
    website: "",
    email: "bhavan.pune.kendra@gmail.com",
  },
  {
    name: "Jaipur",
    position: [26.91962, 75.78781],
    key: "jaipur",
    address:
      "K.M. Munshi Marg, Opp.Dainik Bhaskar, Opp.O.T.S., J.L.N.Marg, Jaipur, 302015",
    maps: "",
    website: "",
    email: "bhavans_ccm@yahoo.co.in",
  },
  {
    name: "Jodhpur",
    position: [26.26841, 73.00594],
    key: "jodhpur",
    address:
      "Amritam, 9, Central School Scheme, Air Force Area, Jodhpur 342 011",
    maps: "",
    website: "",
    email: "",
  },
  {
    name: "Prayagraj",
    position: [25.45, 81.85],
    key: "prayagraj",
    address:
      "5, Nakhas Kohna, Dr. Kailash Nath Katju Road, Prayagraj (Allahabad), 211003",
    maps: "",
    website: "",
    email: "",
  },
  {
    name: "Lucknow",
    position: [26.83928, 80.92313],
    key: "lucknow",
    address:
      "A-7/2, Napier Road Colony, Part I, Thakurganj Chowk, Lucknow 226 003",
    maps: "",
    website: "",
    email: "",
  },
  {
    name: "Bhopal",
    position: [23.25469, 77.40289],
    key: "bhopal",
    address:
      "EMS House, R-11, Press Complex, M.P. Nagar, Zone 1, Bhopal 462 011",
    maps: "",
    website: "",
    email: "",
  },
  {
    name: "New Delhi",
    position: [28.6139, 77.209],
    key: "delhi",
    address: "Mehta Sadan, Kasturba Gandhi Marg, New Delhi 110001",
    maps: "some URL",
    website: "some URL",
    email: "omcherybvb@gmail.com",
  },
];
