import type { Metadata } from "next";
import { Quattrocento } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";

const quattrocento = Quattrocento({
  weight: ["400", "700"],
  preload: true,
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={quattrocento.className}>
        <Header />
        {children}
      </body>
    </html>
  );
}
